#!/usr/bin/env python3
"""Targeted re-promotion for 14 parser-bug-affected nodes.

Two groups of nodes were identified in the schema-drift audit (2026-04-30):

Group A (10 nodes): Entities mistyped as place.location in graph/nodes/locations/.
  - 7 wars -> event.war -> graph/nodes/events/
  - 2 factions -> organization.faction -> graph/nodes/factions/
  - 1 artifact -> object.artifact -> graph/nodes/artifacts/
  These old incorrect files in locations/ are deleted after re-promotion.

Group B (4 nodes): Location nodes with religion-field bleed (WORSHIPS: North etc.)
  in their ## Edges sections. Type is correct (place.location), but edges are
  malformed. These stay in locations/ but are overwritten with corrected output.

Approach (Option B — targeted rebuild, minimal blast radius):
  1. Re-reads the freshly-regenerated infobox-data.jsonl and page-index.jsonl
     (already patched — bugs fixed in wiki-infobox-parser.py).
  2. For each of the 14 slugs: re-emits skeleton via the same logic as
     wiki-pass2-emit-deterministic.py.
  3. Re-reads prose from the existing skeleton bucket artifact (not re-extracting
     from HTML — we use whatever prose was previously extracted and is in the
     bucket's prose/ directory, since prose extraction is not affected by the bugs).
  4. Concatenates skeleton + prose and atomic-renames to the correct target dir.
  5. For Group A: also deletes the old wrong-bucket file in locations/.

Invariants preserved:
  - Atomic-rename: never writes directly to graph/nodes/. Uses a staging temp file.
  - Only the 14 listed nodes change. No other graph/nodes/ files are touched.
  - Reads from working/wiki-parsed/ (freshly regenerated by parser re-run).
  - Does NOT modify working/wiki-pass2/ bucket manifests.

Usage:
  python3 scripts/wiki-pass2-repromote-targeted.py           # dry-run
  python3 scripts/wiki-pass2-repromote-targeted.py --apply   # write files
  python3 scripts/wiki-pass2-repromote-targeted.py -v        # verbose
"""

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path

# ---------------------------------------------------------------------------
# Project paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
INFOBOX_DATA_FILE = PROJECT_ROOT / "working" / "wiki-parsed" / "infobox-data.jsonl"
PAGE_INDEX_FILE = PROJECT_ROOT / "working" / "wiki-parsed" / "page-index.jsonl"
WIKI_PASS2_DIR = PROJECT_ROOT / "working" / "wiki-pass2"
GRAPH_NODES_DIR = PROJECT_ROOT / "graph" / "nodes"

# ---------------------------------------------------------------------------
# The 14 pages to re-promote.
# Each entry: (wiki_page_name, bucket_id, correct_type, original_wrong_type_dir)
# For Group B, original_wrong_type_dir is None (no old file to delete;
# we overwrite in place under the correct locations/ dir).
# ---------------------------------------------------------------------------
TARGETED_PAGES = [
    # Group A: Wars — mistyped as place.location, should be event.war
    ("Spice War",             "locations-other-m-s",   "event.war",              "locations"),
    ("Salt War",              "locations-other-m-s",   "event.war",              "locations"),
    ("Third Turtle War",      "locations-other-s-t",   "event.war",              "locations"),
    ("Second Turtle War",     "locations-other-m-s",   "event.war",              "locations"),
    ("War of Three Princes",  "locations-other-t-y",   "event.war",              "locations"),
    ("War on Dagger Lake",    "locations-other-t-y",   "event.war",              "locations"),
    ("War for the dawn",      "locations-other-t-y",   "event.war",              "locations"),
    # Group A: Factions — mistyped as place.location, should be organization.faction
    ("Second Sons",           "locations-other-m-s",   "organization.faction",   "locations"),
    ("Triarchy",              "locations-other-s-t",   "organization.faction",   "locations"),
    # Group A: Artifact — mistyped as place.location, should be object.artifact
    ("Iron Throne",           "houses-major-recovery", "object.artifact",        "locations"),
    # Group B: Locations with religion-field bleed — type correct, edges malformed
    ("Seven Kingdoms",        "locations-other-s-t",   "place.location",         None),
    ("Pentos",                "locations-other-g-m",   "place.location",         None),
    ("Lys",                   "locations-other-g-m",   "place.location",         None),
    ("Tyrosh",                "locations-other-s-t",   "place.location",         None),
]

# ---------------------------------------------------------------------------
# Type -> directory mapping (mirrors wiki-pass2-promote.py)
# ---------------------------------------------------------------------------
TYPE_DIR_MAP: dict[str, str] = {
    "character.human": "characters",
    "character.direwolf": "characters",
    "character.dragon": "characters",
    "character": "characters",
    "organization.house": "houses",
    "organization.faction": "factions",
    "organization.cult": "factions",
    "organization.religion": "religions",
    "organization": "factions",
    "place.location": "locations",
    "place.region": "locations",
    "place.castle": "locations",
    "place.city": "locations",
    "place": "locations",
    "artifact": "artifacts",
    "artifact.weapon": "artifacts",
    "object": "artifacts",
    "object.artifact": "artifacts",
    "object.text": "texts",
    "event.battle": "events",
    "event.tournament": "events",
    "event.war": "events",
    "event": "events",
    "battle": "events",
    "war": "events",
    "concept": "concepts",
    "concept.culture": "concepts",
    "concept.magic": "concepts",
    "concept.prophecy": "prophecies",
    "concept.theory": "theories",
    "species": "species",
    "title": "titles",
    "prophecy": "prophecies",
    "theory": "theories",
    "text": "texts",
}


def resolve_type_dir(entity_type: str) -> str | None:
    if entity_type in TYPE_DIR_MAP:
        return TYPE_DIR_MAP[entity_type]
    parent = entity_type.split(".")[0]
    if parent in TYPE_DIR_MAP:
        return TYPE_DIR_MAP[parent]
    return None


# ---------------------------------------------------------------------------
# Slug generation (matches wiki-pass2-emit-deterministic.py exactly)
# ---------------------------------------------------------------------------

def page_to_slug(page_name: str) -> str:
    slug = page_name.lower()
    slug = re.sub(r"['\",]", "", slug)
    slug = re.sub(r"[ _]+", "-", slug)
    slug = re.sub(r"[^a-z0-9-]", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug


# ---------------------------------------------------------------------------
# Atomic write helper (mirrors wiki-pass2-promote.py)
# ---------------------------------------------------------------------------

def atomic_write(dest_path: Path, data: bytes) -> None:
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    staging = dest_path.parent / f".staging-{dest_path.name}.tmp"
    try:
        staging.write_bytes(data)
        os.rename(staging, dest_path)
    except Exception:
        try:
            staging.unlink(missing_ok=True)
        except Exception:
            pass
        raise


# ---------------------------------------------------------------------------
# Skeleton renderer (mirrors wiki-pass2-emit-deterministic.py::render_node)
# ---------------------------------------------------------------------------

def wiki_url(page_name: str) -> str:
    import urllib.parse
    encoded = urllib.parse.quote(page_name.replace(" ", "_"), safe="/:@!$&'()*+,;=")
    return f"https://awoiaf.westeros.org/index.php/{encoded}"


def render_edge_line(rel: dict) -> str:
    edge_type = rel.get("edge_type", "UNKNOWN_EDGE")
    target = rel.get("target", "")
    field = rel.get("field", "")
    direction = rel.get("direction", "forward")
    qualifier = rel.get("qualifier", "")

    edge_label = f"{edge_type} (reverse)" if direction == "reverse" else edge_type
    line = f"- {edge_label}: {target} (track_b: {field})"
    if qualifier:
        line += f" [{qualifier}]"
    return line


def render_skeleton(
    page_name: str,
    slug: str,
    entity_type: str,
    aliases: list,
    confidence: str,
    bucket_id: str,
    relationships: list,
    infobox_found: bool,
) -> str:
    url = wiki_url(page_name)

    if aliases:
        alias_items = ", ".join(f'"{a}"' for a in aliases)
        aliases_yaml = f"[{alias_items}]"
    else:
        aliases_yaml = "[]"

    lines = [
        "---",
        f'name: "{page_name}"',
        f"type: {entity_type}",
        f"slug: {slug}",
        f"aliases: {aliases_yaml}",
        f"confidence: {confidence}",
        f'wiki_source: "{url}"',
        f"bucket_id: {bucket_id}",
        "prompt_version: v1-python",
        "node_version: 1",
        "pass_origin: pass2-wiki-deterministic",
        "---",
        "",
        "## Identity",
        "",
        f"{page_name} is a {entity_type} from the AWOIAF wiki.",
        "",
        "## Edges",
        "",
    ]

    if relationships and infobox_found:
        for rel in relationships:
            lines.append(render_edge_line(rel))

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        default=False,
        help="Write new nodes and delete old wrong-type files. Without --apply, dry-run only.",
    )
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        default=False,
        help="Print detailed per-page output.",
    )
    args = parser.parse_args()

    mode = "APPLY" if args.apply else "DRY-RUN"
    print(f"\n=== Targeted re-promotion of 14 parser-bug-affected nodes [{mode}] ===\n")

    # --- Load infobox-data.jsonl ---
    print(f"Loading {INFOBOX_DATA_FILE} ...")
    if not INFOBOX_DATA_FILE.exists():
        print(f"ERROR: {INFOBOX_DATA_FILE} not found. Re-run wiki-infobox-parser.py first.",
              file=sys.stderr)
        sys.exit(1)
    infobox_data: dict[str, dict] = {}
    with open(INFOBOX_DATA_FILE, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            infobox_data[rec["page"]] = rec
    print(f"  {len(infobox_data):,} infobox records loaded")

    # --- Load page-index.jsonl ---
    print(f"Loading {PAGE_INDEX_FILE} ...")
    if not PAGE_INDEX_FILE.exists():
        print(f"ERROR: {PAGE_INDEX_FILE} not found. Re-run wiki-infobox-parser.py first.",
              file=sys.stderr)
        sys.exit(1)
    page_index: dict[str, dict] = {}
    with open(PAGE_INDEX_FILE, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            page_index[rec["page"]] = rec
    print(f"  {len(page_index):,} page-index records loaded\n")

    # --- Process each targeted page ---
    results = []
    errors = []

    for page_name, bucket_id, expected_type, old_type_dir in TARGETED_PAGES:
        slug = page_to_slug(page_name)
        group = "B" if old_type_dir is None else "A"

        if args.verbose:
            print(f"  [{group}] {page_name!r} (slug={slug}, bucket={bucket_id})")

        # 1. Look up infobox data
        infobox_rec = infobox_data.get(page_name)
        page_idx_rec = page_index.get(page_name)

        if infobox_rec is None and page_idx_rec is None:
            msg = f"  WARNING: {page_name!r} not found in infobox-data.jsonl or page-index.jsonl — skipping"
            print(msg, file=sys.stderr)
            errors.append({"page": page_name, "error": "not in parser outputs"})
            continue

        # 2. Determine type — use the expected_type from our override table.
        #    This is already what the patched parser should produce (verified below),
        #    but we use the explicit expected_type as the authoritative value since
        #    this script is a targeted repair operation.
        actual_type = None
        if infobox_rec and infobox_rec.get("entity_type"):
            actual_type = infobox_rec["entity_type"]
        elif page_idx_rec and page_idx_rec.get("entity_type_guess"):
            actual_type = page_idx_rec["entity_type_guess"]

        if actual_type != expected_type:
            print(f"  WARNING: {page_name!r}: parser emits type={actual_type!r}, "
                  f"expected {expected_type!r}. Using expected_type. "
                  f"Check parser fix.", file=sys.stderr)
            errors.append({
                "page": page_name,
                "error": f"type mismatch: parser={actual_type}, expected={expected_type}",
            })
        entity_type = expected_type

        # 3. Aliases and relationships from infobox
        infobox_found = infobox_rec is not None
        aliases: list[str] = []
        relationships: list[dict] = []
        if infobox_rec:
            aliases = infobox_rec.get("aliases") or []
            relationships = infobox_rec.get("relationships") or []

        # 4. Determine confidence from the bucket manifest
        manifest_path = WIKI_PASS2_DIR / bucket_id / "manifest.json"
        confidence = "tier-1"  # default
        if manifest_path.exists():
            try:
                manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
                confidence = manifest.get("tier_default") or "tier-1"
            except (json.JSONDecodeError, OSError):
                pass

        # 5. Render new skeleton
        skeleton_content = render_skeleton(
            page_name=page_name,
            slug=slug,
            entity_type=entity_type,
            aliases=aliases,
            confidence=confidence,
            bucket_id=bucket_id,
            relationships=relationships,
            infobox_found=infobox_found,
        )
        skeleton_bytes = skeleton_content.encode("utf-8")

        # 6. Find existing prose from bucket artifact (if any)
        prose_path = WIKI_PASS2_DIR / bucket_id / "prose" / f"{slug}.prose.md"
        if prose_path.exists():
            prose_bytes = prose_path.read_bytes()
        else:
            prose_bytes = b""

        # 7. Concatenate
        if prose_bytes:
            final_bytes = skeleton_bytes + b"\n" + prose_bytes
        else:
            final_bytes = skeleton_bytes

        # 8. Resolve destination directory
        dest_subdir = resolve_type_dir(entity_type)
        if dest_subdir is None:
            print(f"  ERROR: unrecognised type {entity_type!r} for {page_name!r}",
                  file=sys.stderr)
            errors.append({"page": page_name, "error": f"unknown type dir for {entity_type}"})
            continue
        dest_dir = GRAPH_NODES_DIR / dest_subdir
        dest_path = dest_dir / f"{slug}.node.md"

        # 9. Old wrong-type file path (Group A only)
        old_path = None
        if old_type_dir is not None:
            old_path = GRAPH_NODES_DIR / old_type_dir / f"{slug}.node.md"

        # For Group B (in-place overwrite), check if destination already exists
        # with same content — skip if byte-equal (idempotent).
        outcome = "would_promote"
        if dest_path.exists():
            existing = dest_path.read_bytes()
            if existing == final_bytes:
                outcome = "byte_equal"
            else:
                outcome = "would_overwrite"
        else:
            outcome = "would_promote"

        if args.apply:
            atomic_write(dest_path, final_bytes)
            if outcome == "byte_equal":
                outcome = "skipped_byte_equal"
            elif outcome == "would_overwrite":
                outcome = "overwritten"
            else:
                outcome = "promoted"

            # Group A: delete old wrong-type file
            if old_path and old_path.exists():
                old_path.unlink()
                outcome += "+deleted_old"
        else:
            if old_path and old_path.exists():
                outcome += "+would_delete_old"

        results.append({
            "group": group,
            "page": page_name,
            "slug": slug,
            "entity_type": entity_type,
            "dest": str(dest_path),
            "old_path": str(old_path) if old_path else None,
            "has_prose": bool(prose_bytes),
            "edge_count": len(relationships),
            "infobox_found": infobox_found,
            "outcome": outcome,
        })

        if args.verbose:
            prose_tag = "skeleton+prose" if prose_bytes else "skeleton-only"
            print(f"    type={entity_type} | {len(relationships)} edges | {prose_tag}")
            print(f"    dest: {dest_path}")
            if old_path:
                print(f"    old:  {old_path}")
            print(f"    outcome: {outcome}")
            print()

    # --- Summary ---
    print()
    print("=" * 60)
    print(f"Pages attempted:   {len(TARGETED_PAGES)}")
    print(f"Errors/warnings:   {len(errors)}")
    print()
    print("Results:")
    for r in results:
        prose_tag = "prose" if r["has_prose"] else "skel-only"
        print(f"  [{r['group']}] {r['slug']:<35s} {r['entity_type']:<25s} "
              f"{r['edge_count']:>2} edges  {prose_tag:<10s}  {r['outcome']}")
    print()

    if errors:
        print("Errors / warnings:")
        for e in errors:
            print(f"  {e['page']}: {e['error']}")
        print()

    if not args.apply:
        print("Dry-run complete. Run with --apply to write files.")
    else:
        promoted = sum(1 for r in results if "promoted" in r["outcome"] or "overwritten" in r["outcome"])
        deleted = sum(1 for r in results if "deleted_old" in r["outcome"])
        skipped = sum(1 for r in results if "byte_equal" in r["outcome"])
        print(f"Files written/overwritten: {promoted}")
        print(f"Old wrong-type files deleted: {deleted}")
        print(f"Byte-equal (skipped): {skipped}")
    print("=" * 60)


if __name__ == "__main__":
    main()
